### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PoloNX** [suchmememanyskill/switch-90dns-setter#1]
Hi, how did you convert 163.172.141.219 to u32 like 0xdb8daca3 ?

**Comment by suchmememanyskill** [comment]
I think i originally got these by using setsysGetNetworkSettings with the right dns' set

But it's not overly tricky to reverse engineer:

An ipv4 address is a 32 bit number. Each number of an ipv4 address in decimal represents 8 bits. 8 bits can be represented as 2 hexadecimal characters (1 hex character is 4 bits)

163 = 0xA3
172 = 0xAC
141 = 0x8D
219 = 0xDB

This would make 0xA3AC8DDB, but that isn't right. For this endianness comes into play. Endianness indicates what order a bytes are stored in. Little endian means the smallest byte is stored first, big endian means the biggest byte is stored first. The above number is little endian: the smallest end is stored first. If we reverse this:

0x(A3)(AC)(8D)(DB)
0x(DB)(8D)(AC)(A3)
0xDB8DACA3

We get the correctly converted dns ip

**Comment by PoloNX** [comment]
Thanks !
